services:
  - type: web
    name: chat-obs
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: TWITCH_CHANNEL
        value: funilzinha
      - key: YOUTUBE_CHANNEL_ID
        value: UC5ooSCrMhz10WUWrc6IlT3Q
    autoDeploy: true
    healthCheckPath: /health
    initialDelay: 60