services:
  - type: web
    name: chat-obs
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: TWITCH_CHANNEL
        value: funilzinha
      - key: YOUTUBE_CHANNEL_ID
        value: UC5ooSCrMhz10WUWrc6IlT3Q
      - key: YOUTUBE_API_KEY
        sync: false 
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache